### ISSUE TITLE
The code doesnt have AwsCognitoJwtVerifier class, does this work ?

### ISSUE THREAD

**Issue by krallapalli** [IxorTalk/ixortalk.aws.cognito.jwt.security.filter#1]

**Comment by ddewaele** [comment]
Updated the code / README.
Should work now ... working on a sample spring boot app / AWS cognito cloudformation so you can get started quickly with it.

**Comment by dostiharise** [comment]
@ddewaele  Thanks for the README! Useful as a reference for me, not many open source libraries out there that do this. 

Let me know if you need help. I can contribute a few pull requests, since I am working on the same.

**Comment by ddewaele** [comment]
Added a couple of other repo's that you might find interesting

- [Spring Boot Sample App to showcase the library](https://github.com/IxorTalk/ixortalk.aws.cognito.jwt.sampleapp)
- [NodeJS CLI app for Cognito Token Retrieval](https://github.com/IxorTalk/ixortalk.aws.cognito.token.retrieval)
- [AWS Cognito CloudFormation Templates](https://github.com/IxorTalk/ixortalk.aws.cognito.cloudformation)

Feel free to take a look at them and provide feedback.

**Comment by ddewaele** [comment]
Closing this issue for now
