### ISSUE TITLE
clearContext on exception

### ISSUE THREAD

**Issue by xanscale** [IxorTalk/ixortalk.aws.cognito.jwt.security.filter#12]
on [AwsCognitoJwtAuthenticationFilter](https://github.com/IxorTalk/ixortalk.aws.cognito.jwt.security.filter/blob/master/src/main/java/com/ixortalk/aws/cognito/boot/filter/AwsCognitoJwtAuthenticationFilter.java)
on catch exception library clean Context (row 62)

I think it's useless and problematic:

useless) you don't set authentication before so is useless to clear it
problematic) i have another filter that put something there and in this way you clear my things :(

can you remove this row, or can explain me the porpuse?

@ddewaele thz for this library

**Comment by xanscale** [comment]
i can make a pull requests, if you consider is usefull

**Comment by ddewaele** [comment]
Can you describe you use-case with the library ?  Do you want to have some kind of fallback mechanism in place when the Jwt Authentication fails (and use another authenication mechanism ?)

I think it's a common practice to clear the security context upon an exception in a security filter (ex: BasicAuthenticationFilter does exactly the same, catching the exception and clearing the securitycontext.
 
But happy to hear about your use case and seeing how we can facilitate it.

**Comment by xanscale** [comment]
"and use another authenication mechanism?" simply YES

we need to use AWS Cognito and a custom sso

i hava another filter that create your JwtAuthentication in same format but using different logic

with this works perfectly
https://github.com/xanscale/ixortalk.aws.cognito.jwt.security.filter/commit/9d74796ba6974de7859cdf3cf87bd9c004089828


instead of clear security context i used

`.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)`

**Comment by ddewaele** [comment]
Is your filter made part of the spring security filter chain ? If so you can run it after the AwsCognitoJwtAuthenticationFilter. The AwsCognitoJwtAuthenticationFilter will clear the security context but your filter can then fill it up.

Would that be an option ?

I did log issue #13 just now to point out that spring can register the filter twice when not providing a custom FilterRegistrationBean to exclude it.

**Comment by xanscale** [comment]
i will try your #13 suggestion, but in this way how set order? can you show me code for registering 2 filter in specific order?

**Comment by xanscale** [comment]
go further on other thread
