### ISSUE TITLE
Verifying the JWT token signature

### ISSUE THREAD

**Issue by lakshayghai** [IxorTalk/ixortalk.aws.cognito.jwt.security.filter#4]
Hi,

I was going through the code and was not able to find where you are Verifying token Signature.
Can you point me to the place where you are doing the Step 2  (Verifying the JWT token signature)

**Comment by ddewaele** [comment]
The ConfigurableJWTProcessor (from the [com.nimbusds.jwt library](http://nimbusds.com/blog/category/jwt/)) used in the AwsCognitoIdTokenProcessor class will verify the signature of the JWT Token. https://github.com/IxorTalk/ixortalk.aws.cognito.jwt.security.filter/blob/c8483250ec0c1f4b7419b6eda3f25f721d04864c/src/main/java/com/ixortalk/aws/cognito/boot/filter/AwsCognitoIdTokenProcessor.java#L67

**Comment by lakshayghai** [comment]
Got it, Followed the the code. Thanks
