### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by ronesim** [IxorTalk/ixortalk.aws.cognito.jwt.security.filter#5]
I was looking through the code and I found out that classes: _AwsCognitoAutoConfiguration_, _AwsCognitoCredentialsHolder_, _AwsCognitoJtwConfiguration_, _JwtAuthenticationProvider_ are not used. Moreover _JwtAutoConfiguration_, _JwtConfiguration_ and _JwtIdTokenCredentialsHolder_ are doing the same thing. Can you clarify me this thing please? Am I missing something?

**Comment by aurelienmarie** [comment]
+1

Some classes look exactly the same. The purpose of the classes aren't well documented.

**Comment by aurelienmarie** [comment]
I've personally removed all the "AWSCognito*". Kept only the "JWT*" classes and still works.
Also i've added some Lombok annotations to make code clearer. Works like a charm, Thank you IxorTalk.
